version: '3'
services:
  service-a:
    build:
      context: ./swagger
      dockerfile: Dockerfile
    ports:
      - 3001:3001
  service-b:  
    build:    
      context: ./booking-app 
      dockerfile: Dockerfile 
    ports: 
      - 3002:3002
          
  api-gateway:      
     build:
       context: ./
       dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
     - service-a
     - service-b